### ISSUE TITLE
ParametersRequest is not serializable by Jackson due to no default constructor

### ISSUE THREAD

**Issue by daniellavoie** [spring-projects/spring-credhub#24]
I fear some other request entities might be impacted by this.

```
org.springframework.credhub.core.CredHubException: Error calling CredHub: 500: {"timestamp":1508958226409,"status":500,"error":"Internal Server Error","exception":"org.springframework.beans.BeanInstantiationException","message":"Failed to instantiate [org.springframework.credhub.support.ParametersRequest]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.credhub.support.ParametersRequest.<init>()","path":"/credhub-server-mock/api/v1/data"}
	at org.springframework.credhub.core.CredHubTemplate.doWithRest(CredHubTemplate.java:359)
	at org.springframework.credhub.core.CredHubTemplate.generate(CredHubTemplate.java:129)
```

**Comment by daniellavoie** [comment]
It appears that `spring-credhub` entities aren't modelized like default Pojo expected by Jackson. To serialized these entities, a custom configured `ObjectMapper` is embedded in the `CredHubTemplate` configuration.
